name = "bare_screens"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[configuration.variables]
device = { type = "Enum", values = ["ili9341", "otm8009a", "ssd1306", "ST7735R"], default = "otm8009a" }

[[depends-on]]
bare_types = "0.1.0-dev"
bare_hal = "0.1.0-dev"
